version: '3'

services:
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "4442:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: MongoDB

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: RedisStack

  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    ports:
      - "5432:5432"
    container_name: PostgreSQL

  mysql:
    image: bitnami/mysql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    container_name: MySQL

  mariadb:
    image: bitnami/mariadb:latest
    ports:
      - "3307:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    container_name: MariaDB

  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - "mysql:db"
    ports:
      - "8080:80"
    container_name: phpMyAdmin

